config/routes.rb
Rails.application.routes.draw do
    

  match 'user-test',  to: 'user_test#index', via: [:get, :post], as: :user_test_search
  get 'user-test/new', to: 'user_test#new'
  post 'user-test/create', to: 'user_test#create'

  get 'user-test/search_user', to: 'user_test#search_user'

  match 'analytics',  to: 'analytics#index', via: [:get, :post], as: :analytic_search
  get 'analytics/view/:id', to: 'analytics#show'
  post 'analytics/retake/:id', to: 'analytics#retake', as: :retake_user_analytic
  post 'analytics/delete/:id', to: 'analytics#delete', as: :delete_user_analytic

  get 'dashboard', to: "users#dashboard", as: :dashboard
  match 'user-candidates',  to: 'users#index', via: [:get, :post], as: :user_search
  get  'users/new',  to: 'users#new'
  post  'users/delete/:id',  to: 'users#delete', as: :delete_user
  get  'users/edit/:id',  to: 'users#edit'
  get  'users/invite/:id',  to: 'users#edit'
  patch 'users/update',  to: 'users#update', as: :update_user
  post 'users/create',  to: 'users#add_user'

 
  get 'result', to: 'take_test#result'
  get 'take-test/:id', to: 'take_test#take_test'
  post 'submit-test', to: "take_test#submit_test", as: :submit_test
  get 'profile', to: "take_test#profile", as: :profile
  post 'update-profile',  to: 'take_test#update_profile', as: :update_profile

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => { :registrations => 'member_registrations' }

  get 'test-library/preview-test/:id', to: 'tests#preview_test'

  match 'test-library',  to: 'tests#index', via: [:get, :post], as: :test_search

  post 'test-library/delete/:id', to: 'tests#delete_test', as: :delete_test_index

  get 'tests/new/:id', to: "tests#new", as: :new_test

  delete 'tests/delete/:id', to: "tests#delete", as: :delete_test

  post 'tests/update_status/:id', to: "tests#update_status"

  post 'tests/create', to: "tests#create"

  post 'tests/create_test_question', to: "tests#create_test_question"

  mount Ckeditor::Engine => '/ckeditor'
  match 'questions',  to: 'questions#index', via: [:get, :post], as: :question_search
  get 'questions/new', to: 'questions#multiple_choice'
  post 'questions/delete/:id', to: 'questions#delete_multiple_choice', as: :delete_question
  get 'questions/edit/:id', to: 'questions#edit_multiple_choice', as: :edit_question
  post 'questions/update', to: 'questions#update_multiple_choice', as: :update_question
   match 'results',  to: 'results#index', via: [:get, :post], as: :result_search
  post 'results/create', to: 'results#result_create'
  post 'results/delete/:id', to: 'results#delete', as: :delete_result
  get 'results/edit/:id', to: 'results#edit', as: :edit_result
  post 'results/update', to: 'results#update', as: :update_result

  post 'questions_multiple_choice/create', to: 'questions#multiple_choice_create'
  post 'questions-section/create', to: 'questions#question_section_create'

  match 'print',  to: 'print_report#index', via: [:get, :post], as: :print_search
  get 'print/report', to: 'print_report#print_report'
  get 'print/single-report', to: 'print_report#print_single_report'
  match 'question-sections',  to: 'question_sections#index', via: [:get, :post], as: :question_sections_search
  post 'question-sections/create', to: 'question_sections#result_create'
  post 'question-sections/delete/:id', to: 'question_sections#delete', as: :delete_question_sections
  get 'question-sections/edit/:id', to: 'question_sections#edit', as: :edit_question_sections
  post 'question-sections/update', to: 'question_sections#update', as: :update_question_sections

  match 'years',  to: 'years#index', via: [:get, :post], as: :years_search
  post 'years/create', to: 'years#result_create'
  post 'years/delete/:id', to: 'years#delete', as: :delete_years
  get 'years/edit/:id', to: 'years#edit', as: :edit_years
  post 'years/update', to: 'years#update', as: :update_years

  match 'courses',  to: 'courses#index', via: [:get, :post], as: :courses_search
  post 'courses/create', to: 'courses#result_create'
  post 'courses/delete/:id', to: 'courses#delete', as: :delete_courses
  get 'courses/edit/:id', to: 'courses#edit', as: :edit_courses
  post 'courses/update', to: 'courses#update', as: :update_courses

  match 'sections',  to: 'sections#index', via: [:get, :post], as: :sections_search
  post 'sections/create', to: 'sections#result_create'
  post 'sections/delete/:id', to: 'sections#delete', as: :delete_sections
  get 'sections/edit/:id', to: 'sections#edit', as: :edit_sections
  post 'sections/update', to: 'sections#update', as: :update_sections

   get 'settings', to: 'users#setting'

  get 'myquestions/index'

  get 'myquestions/create'

  get 'myquestions/update'

  get 'myquestions/delete'

  get 'terms-conditions', to: 'home#terms_conditions'

  root 'home#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :question_answers
	belongs_to :question_section
	validates :question_name, :question_section_id, presence: true


	 # scope :get_question, lambda {||
	 # 		find_by_sql([" 
		# 				select q.id, q.question_name, q.created_at, qs.question_section_name from questions q
		# 			INNER JOIN question_sections as qs on qs.id = q.question_section_id
		# "])
	 # }



  		def self.get_question()
		  	Question.find_by_sql([" 				
					select q.id, q.question_name, q.created_at, qs.question_section_name from questions q
					INNER JOIN question_sections as qs on qs.id = q.question_section_id
			"]) 
  		end

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_role

  def index

    @page_header = "All Questions"
    @page_desc = "View all questions"

    # @question = Question.get_question
    # select q.id, q.question_name, q.created_at, qs.question_section_name from questions q
    #       INNER JOIN question_sections as qs on qs.id = q.question_section_id
    
    if params[:title].blank?
     @question = Question.joins(:question_section).select("questions.id, questions.question_name, questions.created_at, question_sections.question_section_name").where("questions.status = 'active'").order("questions.id desc").paginate(:page => params[:page], :per_page => 15)
    else
     @question = Question.joins(:question_section).select("questions.id, questions.question_name, questions.created_at, question_sections.question_section_name").order("questions.id desc").where("questions.status = 'active' and lower(questions.question_name) like '%#{params[:title].downcase}%' " ).paginate(:page => params[:page], :per_page => 15)
     # render :layout => false
    end

    # .where("bars.foo_id != ? and users.created_at <= ?", 5, 50.days.ago).select("distinct users.*") 
  end


  def multiple_choice

    @page_header = "Question Management"
    @page_desc = "Create new questions"
  	@q_section = QuestionSection.where(status: "active")
    @result = Result.where(status: "active")

  end

  def analytics
    @page_header = "Analytics"
    @page_desc = "Results Analytics"
  end

  # def test_library
  #   @page_header = "Test Library"
  #   @page_desc = "View questions library"
  # end


  def multiple_choice_create
  		@question = Question.new(q_params)
  		# @question.question_type_id = 1
  		#save the question
      q_ans = params[:question_ans].reject { |q| q[:answer].blank? || q[:result].blank?}
  		if @question.save && q_ans.present?
  			# question_ans[q_answer]
  			#save the question answer
	  	        # q_ans = params[:question_ans].reject { |q| q[:answer].blank? || q[:result].blank? }
              # q_result = params[:question_ans].reject { |q| q[:result].blank? }
	  	        q_ans.each_with_index do |p, index|      
                qa = QuestionAnswer.new()
	      				qa.question_answer_name = p[:answer] 
                qa.result_id = p[:result] 
	      				qa.question_id = @question.id
	      				if qa.save
	      				end
	  	        end

          check_exist = TestQuestion.where(question_section_id: @question.question_section_id).first
          if check_exist.present?
            tq = TestQuestion.new()
            tq.question_id = @question.id
            tq.test_id = check_exist.test_id 
            tq.question_section_id = @question.question_section_id
            if tq.save
            end
          end
        @result = true          
  		else

  		end
  		 # render :inline => "success"
       render :layout => false
  		 # debug :params
  end



  def update_multiple_choice
    if Question.update(params[:question_id],q_params)
      q_ans = params[:question_ans].reject { |q| q[:answer].blank? || q[:result].blank?}
      if q_ans.present?
            QuestionAnswer.where(question_id: params[:question_id]).destroy_all
              q_ans.each_with_index do |p, index|      
                qa = QuestionAnswer.new()
                qa.question_answer_name = p[:answer] 
                qa.result_id = p[:result] 
                qa.question_id = params[:question_id]
                if qa.save
                end
              end

        @result = true          
      else

      end
    end
    render :layout => false
    # render :inline => "success"

  end

  def edit_multiple_choice
    @page_header = "Question Management"
    @page_desc = "Edit questions"
    @question = Question.find(params[:id])
    @question_ans = QuestionAnswer.where(question_id: params[:id])
    @q_section = QuestionSection.all
    @result = Result.where(status: "active")
  end

  def delete_multiple_choice  
    # @q = Question.where(id: params[:id]).destroy_all
    @q =  Question.update(params[:id], status: "archived")
    @tq = QuestionAnswer.where(question_id: params[:id]).destroy_all
    @question = Question.joins(:question_section).select("questions.id, questions.question_name, questions.created_at, question_sections.question_section_name").where("questions.status = 'active'").order("questions.id desc").paginate(:page => params[:page], :per_page => 15)
    render :layout => false
  end

 
  def question_section_create
  	@q_section = QuestionSection.new(q_section_params)
  		#save the question
  		if @q_section.save 	
  			respond_to do |format|
			format.js
			format.html { render :partial => QuestionSection.order("created_at desc") }
			end

  		else
  			@result = false
  		end
  			@q_section = QuestionSection.all
  end




private



  def q_params
    	params.require(:question).permit(:question_name, :question_point, :question_section_id)
  end

  

  def q_section_params
    	params.require(:question_section).permit(:question_section_name)
  end

  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question_pagination.html.erb
 <%= will_paginate @question, renderer: BootstrapPagination::Rails  %>

 <!-- , :params => { :controller => "questions", :action => "index"} -->

app/views/questions/_question_partial.html.erb
<table class="table table-hover">
  <tbody><tr>

    <th>Question Title</th>
    <th>Section</th>
    <th>Published</th>
    <!-- <th>Report</th> -->
    <th>Actions</th>
  </tr>
  <%@question.each do |q|%>
    <tr>

      <td><%=simple_format(q.question_name)%></td>
      <td><%=q.question_section_name%></td>
      <td><%=q.created_at.to_date.strftime("%m-%d-%Y")%></td>
      <!-- <td>Report</td> -->
      <td>
      <div class="width-130">
      <a class="btn btn-warning "  data-toggle="tooltip" title="Edit"  href="/questions/edit/<%=q.id%>" role="button"><i class="fa fa-edit"></i></a>
      <%= link_to "<i class='fa fa-archive'></i>".html_safe, delete_question_path(q.id),  data: {confirm: "Are you sure Archive"}, :method => :post, class: "btn btn-danger", remote: true, "data-toggle" => "tooltip", :title => "Archive", "data-caption" => "Yes, archive it"   %>

       </div>   
      </td>
    </tr>
  <%end%>
</tbody></table>

app/views/questions/_question_section_partial.html.erb
<select name="question[question_section_id]" class="q_section-select form-control"> 
<option value="">Select Location</option>
<%= grouped_options_for_select [['Search Section',  QuestionSection.all.collect {|v| [ v.question_section_name, v.id ] }]]%>
</select>

app/views/questions/delete_multiple_choice.js.erb
$('.question_index_ajax').html("<%= escape_javascript(render partial: 'question_partial',  :locals => { :question => @question}) %>");
swal(
  'Good job!',
  'Successfully Archived!',
  'success'
)

app/views/questions/edit_multiple_choice.html.erb
<div class="info-box"> 
  <div class="content">
     <%= form_for :question, url: update_question_path, :html => {id: "multiple-choice-form", class: "form-horizontal", :multipart => true}, remote: true do |f| %>
          <%=hidden_field_tag :question_id, params[:id]%>
          <div class="form-group has-feedback required">
             <div class="col-sm-2">
            <%=f.label :question_name, "Question Section:"%>
            </div>
            <div class="col-sm-10 col-lg-4 question_section_ajax">
              <select name="question[question_section_id]" class="q_section-select form-control"> 
              <option value="">Select Location</option>
              <%= grouped_options_for_select [['Search Section',  @q_section.collect {|v| [ v.question_section_name, v.id ] }]], @question.question_section_id%>
              </select>
            </div>  
             <span class="help-blockx pull-rxight"><a class="q_section_modal" data-turbolinks="false" href="javascript:void(0);"><i class='fa fa-plus'></i> Add New Section</a></span>
          </div>
<hr>
          <div class="form-group has-feedback required">
              <div class="col-sm-2">
              <%=f.label :question_name, "Question:"%>
              </div>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_area :question_name, value: "#{@question.question_name}", :class => 'ckeditor form-control' %>
               
            </div>
          </div>
         <div id="q_answer">
         <%@question_ans.each_with_index do |q, index|%>
          <%q_count = index + 1%>
            <hr/>
            <div class="q_append form-group has-feedback required">
            <div class="col-sm-2">
                <%=f.label :question_name, "Option #{q_count}:"%>
              </div>
              <div class="col-sm-8 col-lg-8">
              <%q.question_answer_name%>
                <%= text_area_tag "question_ans[][answer]", q.question_answer_name, id: "option_ans#{index}",  :class => 'ckeditor form-control' %>
                <span class="help-block pull-right"> Result: 
                 <select name="question_ans[][result]" class="q_result-select question_result form-control"> 
                  <option value="">Select Result</option>
                  <%= grouped_options_for_select [['Search Result',  @result.collect {|v| [ v.title, v.id ] }]],q.result_id%>
                 
                  </select> 
                  </span>
            </div>
               <div class="col-sm-2 col-lg-2">
               </div>
            </div>
          <%end%>
          </div>  

        <div class="form-group">
        <div class="col-sm-10 col-xs-12 col-lg-10">
      <span class="help-block pull-right"><a class="add_question" data-turbolinks="false" href="javascript:void(0);"> <i class='fa fa-plus'></i> Add New Answer</a></span>
      </div>
      </div>
        <div class="form-group">
        <div class="col-sm-offset-2  col-sm-10 col-lg-offset-2 col-lg-9">
          <button class="btn btn-primary btn-flat" type="submit" name="commit" value="save"> <i class='fa fa-savex'></i> Save Changes
          </button>
</div>
        </div>
      </div>
       <%end%>
  </div>
</div>




<!-- Modal for create section -->
<div class="modal fade" id="q_section_modal" tabindex="1" role="dialog" aria-labelledby="myModalLabel2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2"><i class="fa fa-file-text-o"></i> Create Section</h4>
      </div>

      <%= form_for :question_section, url: questions_section_create_path, :html => {id: "q_section_form", class: "form-horizontal", :multipart => true}, :remote => true do |f| %>
      <div class="modal-body">
        
          <div class="form-group has-feedback required">
              <%=f.label :question_section_name, "Question Section:", class: "col-sm-3 control-label"%>
            <div class="col-sm-10 col-lg-8">
              <%= f.text_field :question_section_name, :class => 'form-control' %>
              <span class="help-block pull-right">Enter Question Section Name</span>
            </div>
          </div>

      </div>
      
      <div class="modal-footer">
       <!-- <button type="button" class="btn btn-default btn-flat" type="submit" name="commit" value="Save">Save</button> -->
       <%= f.submit "Save", class: "btn btn-default btn-flat" %>
        <button class="btn btn-default btn-flat" data-dismiss="modal" >Cancel</button>

      </div>
      <%end%>
    </div>
  </div>
</div>


<script type="text/javascript">

    // CKEDITOR.replace( 'question_question_name' );



  function func_correct_answer(id){

// idx = CKEDITOR.instances['option_ans'+id].getData();
      // for(var i in (this).length) {
      //   alert(i);
      // }

      // $(".ans").each(function( index ) {
      //   $('#key-ans'+index).val("");


    $('#key-answer').val(id);
  // console.log( index + ": " + $( this ).text() );
};

        
      // $('#key-ans'+id).val(id);


     // var ck = CKEDITOR.instances
     // var ed = id
     // alert($('#key-ans'+id).val(id));

      // alert(CKEDITOR.instances.ed.getData());


  // var n = $(this).length;
    // alert(id);
// var value = CKEDITOR.instances[ids].getData();
// CKEDITOR.instances.+ids+.getData();

// idx = CKEDITOR.instances['option_ans'+id].getData();

     // var ck = CKEDITOR.instances
     // var ed = id
     // alert(idx);

      // alert(CKEDITOR.instances.ed.getData());


// var editor = CKEDITOR.replace("id");

// The "change" event is fired whenever a change is made in the editor.
// editor.on( 'change', function( evt ) {
    // getData() returns CKEditor's HTML content.
    // console.log( 'Total bytes: ' + evt.editor.getData().length );
// });


    // alert(id);
    // var ck = id;
    // var data = CKEDITOR.instances +'.' +  + id + '.' + getData();
    //   alert(data);
  // alert (CKEDITOR.instances[3].getData()); 
    // var myinstances = [];

//this is the foreach loop
for(var i in CKEDITOR.instances) {

   /* this  returns each instance as object try it with alert(CKEDITOR.instances[i]) */
    CKEDITOR.instances[i]; 
   
    /* this returns the names of the textareas/id of the instances. */
    CKEDITOR.instances[i].name;

    /* returns the initial value of the textarea */
    CKEDITOR.instances[i].value;  
 
   /* this updates the value of the textarea from the CK instances.. */
   CKEDITOR.instances[i].updateElement();

   /* this retrieve the data of each instances and store it into an associative array with
       the names of the textareas as keys... */
   myinstances[CKEDITOR.instances[i].name] = CKEDITOR.instances[i].getData(); 
   // alert(myinstances[CKEDITOR.instances[i].name]);
   // alert (CKEDITOR.instances[i].getData() );
// }

  }

$(function() {

// CKEDITOR.instances['textareaId'].setData(value);


        var scntDiv = $('#q_answer');
        var i = $('#q_answer hr').size() + 1;
        
        $('.add_question').on('click', function() {

          // alert("s");
                $('<div class="q_new"><hr/> <div class="form-group has-feedback required"> \
            <div class="col-sm-2"> \
                <label for="question_question_name">Option ' + i +':</label> \
              </div>  \
              <div class="col-sm-8 col-lg-8">  \
                <textarea name="question_ans[][answer]" id="option_ans' + i +'" class="ckeditor form-control"></textarea>  \
                <span class="help-block pull-right"> Result:  \
                 <select name="question_ans[][result]" class="q_result-select question_result form-control">   \
                  <option value="">Select Result</option> \
                      <optgroup label="Search Result"> \
                      <%@result.each do |r|%> \
                      <option value="<%=r.id%>"><%=r.title%> </option> \
                      <%end%> \
                      </optgroup> \
                  </select> \
                  </span>\
            </div>\
               <div class="col-sm-2 col-lg-2">\
                <a data-turbolinks="false" href="#" id="remScnt"><i class="fa fa-close"></i> Remove</a> \
               </div>\
            </div></div>').appendTo(scntDiv);

                      CKEDITOR.replace( 'option_ans' + i  );
                      $(".q_result-select").select2({
                           placeholder: "Select Result",
                           allowClear: true
                        });
                          $('html, body').stop().animate({
                            scrollTop: $(".main-footer").offset().top
                        }, 1000);
                          
                i++;

                return false;
        });
        $(document).on("click", "#remScnt",function (e){
        // $('#remScnt').on('click','html' function() { 
          // alert("s");
                if( i > 2 ) {
                        $(this).parents('.q_new').remove();
                        i--;
                }
                return false;
        });
});



// $('#addScnt').live('click', function() {
//                 $('<p><label for="p_scnts"><input type="text" id="p_scnt" size="20" name="p_scnt_' + i +'" value="" placeholder="Input Value" /></label> <a href="#" id="remScnt">Remove</a></p>').appendTo(scntDiv);
//                 i++;
//                 return false;
//         });





</script>

app/views/questions/index.html.erb
<!-- Main content -->

<div class="row">
  <div class="col-xs-12">
       <a href="/questions/new" class="pull-right btn btn-primary btn-createtest"><i class="fa fa-plus"></i> Create New Questions</a>
  </div>
</div>


  <div class="row">
        <div class="col-xs-12">
          <div class="box box-main">
            <div class="box-header with-border">
              <h3 class="box-title">Question List</h3>

              <div class="box-tools">
               <%=form_tag(question_search_path, method: "GET", :id => "search-inputx", remote: true ) do -%>   
                <div style="width: 200px;" class="input-group input-group-sm">
                  <div class="input-group-btn">
                    <a href="/questions" class="btn btn-default"><i class="fa fa-refresh"></i></a>
                  </div>
                    <%= text_field_tag(:title, nil, class: 'form-control pull-right',  placeholder: 'Search Title', value: params[:title]) -%>
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                  </div>
              </div>
               <%end%>
            </div>

            </div>
            <!-- /.box-header -->
     
            <div class="box-body question_index_ajax table-responsive no-padding">
              <%=render partial: "question_partial",  :locals => { :question => @question}%>
            </div>
              <div class="box-footer ajax-pagination">
                    <%= will_paginate @question, renderer: BootstrapPagination::Rails %>
              </div>
             
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>

  </div>


<!-- Modal -->
<div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
<!--         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
        <h4 class="modal-title" id="myModalLabel">Confirmation</h4>
      </div>
      <div class="modal-body">
         Are you sure you want to delete?
      </div>
      <div class="modal-footer">
       <!-- <button type="button" class="btn btn-danger" id="delete">Delete</button> -->
       <%#= link_to 'Delete', delete_ad_path(17, s: params[:s]), method: :delete, :class => 'btn btn-danger' %>

       <a href="#" data-method="delete" rel="nofollow" class="btn btn-danger btn-delete-ad">Delete</a>
       <button type="button" data-dismiss="modal" class="btn">Cancel</button>
      </div>
    </div>
  </div>
</div>



<!-- Modal for create section -->
<div class="modal fade" id="t_create_modal" tabindex="1" role="dialog" aria-labelledby="myModalLabel2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2"><i class="fa fa-file-text-o"></i> Create Test</h4>
      </div>

      <%= form_for :tests, url: tests_create_path, :html => {id: "test_form", class: "form-horizontal", :multipart => true}, :remote => true do |f| %>
      <div class="modal-body">
        
          <div class="form-group has-feedback required">
              <%=f.label :test_name, "Test Name:", class: "col-sm-3 control-label"%>
            <div class="col-sm-10 col-lg-8">
              <%= f.text_field :test_name, :class => 'form-control' %>
              <span class="help-block pull-right">Enter Test Name</span>
            </div>
          </div>

      </div>
      
      <div class="modal-footer">
       <!-- <button type="button" class="btn btn-default btn-flat" type="submit" name="commit" value="Save">Save</button> -->
       <%= f.submit "Save", class: "btn btn-default btn-flat" %>
        <button class="btn btn-default btn-flat" data-dismiss="modal" >Cancel</button>

      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/questions/index.js.erb
$('.question_index_ajax').html("<%= escape_javascript(render partial: 'question_partial',  :locals => { :question => @question}) %>");
$('.ajax-pagination').html("<%= escape_javascript(render partial: 'question_pagination',  :locals => { :question => @question}) %>");

app/views/questions/multiple_choice_create.js.erb
<%if @result == true%>
swal(
  'Good job!',
  'Successfully Saved!',
  'success'
)
 $('#q_section_form')[0].reset();


 $('.q_section-select').select2("val", "");
$('#multiple-choice-form')[0].reset();
for (instance in CKEDITOR.instances){
   CKEDITOR.instances[instance].setData(" ");
}

 $(".q_result-select").select2("val", "");



<%else%>
swal(
  'Oops...',
  'Please check your entries or fill up the blanks before you submit, and try again.',
  'error'
)

<%end%>

app/views/questions/question_section_create.js.erb
<%unless @result == false%>
swal(
  'Good job!',
  'Successfully Saved!',
  'success'
)

$('.question_section_ajax').html("<%= escape_javascript(render partial: 'question_section_partial',  :locals => { :q_section => @q_section}) %>");
 $('#q_section_form')[0].reset();
 $('#q_section_modal').modal('hide');

$(".q_section-select").select2({
	placeholder: "Select Section",
	allowClear: true
});



<%else%>
swal(
  'Oops...',
  'Something went wrong!',
  'error'
)
<%end%>

app/views/questions/test_library.html.erb
Coming Soon!

app/views/questions/update_multiple_choice.js.erb
<%if @result == true%>
 
swal(
  'Good job!',
  'Successfully Updated!',
  'success'
)

<%else%>
swal(
  'Oops...',
  'Something went wrong!',
  'error'
)

<%end%>