config/routes.rb
Rails.application.routes.draw do
    

  match 'user-test',  to: 'user_test#index', via: [:get, :post], as: :user_test_search
  get 'user-test/new', to: 'user_test#new'
  post 'user-test/create', to: 'user_test#create'

  get 'user-test/search_user', to: 'user_test#search_user'

  match 'analytics',  to: 'analytics#index', via: [:get, :post], as: :analytic_search
  get 'analytics/view/:id', to: 'analytics#show'
  post 'analytics/retake/:id', to: 'analytics#retake', as: :retake_user_analytic
  post 'analytics/delete/:id', to: 'analytics#delete', as: :delete_user_analytic

  get 'dashboard', to: "users#dashboard", as: :dashboard
  match 'user-candidates',  to: 'users#index', via: [:get, :post], as: :user_search
  get  'users/new',  to: 'users#new'
  post  'users/delete/:id',  to: 'users#delete', as: :delete_user
  get  'users/edit/:id',  to: 'users#edit'
  get  'users/invite/:id',  to: 'users#edit'
  patch 'users/update',  to: 'users#update', as: :update_user
  post 'users/create',  to: 'users#add_user'

 
  get 'result', to: 'take_test#result'
  get 'take-test/:id', to: 'take_test#take_test'
  post 'submit-test', to: "take_test#submit_test", as: :submit_test
  get 'profile', to: "take_test#profile", as: :profile
  post 'update-profile',  to: 'take_test#update_profile', as: :update_profile

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => { :registrations => 'member_registrations' }

  get 'test-library/preview-test/:id', to: 'tests#preview_test'

  match 'test-library',  to: 'tests#index', via: [:get, :post], as: :test_search

  post 'test-library/delete/:id', to: 'tests#delete_test', as: :delete_test_index

  get 'tests/new/:id', to: "tests#new", as: :new_test

  delete 'tests/delete/:id', to: "tests#delete", as: :delete_test

  post 'tests/update_status/:id', to: "tests#update_status"

  post 'tests/create', to: "tests#create"

  post 'tests/create_test_question', to: "tests#create_test_question"

  mount Ckeditor::Engine => '/ckeditor'
  match 'questions',  to: 'questions#index', via: [:get, :post], as: :question_search
  get 'questions/new', to: 'questions#multiple_choice'
  post 'questions/delete/:id', to: 'questions#delete_multiple_choice', as: :delete_question
  get 'questions/edit/:id', to: 'questions#edit_multiple_choice', as: :edit_question
  post 'questions/update', to: 'questions#update_multiple_choice', as: :update_question
   match 'results',  to: 'results#index', via: [:get, :post], as: :result_search
  post 'results/create', to: 'results#result_create'
  post 'results/delete/:id', to: 'results#delete', as: :delete_result
  get 'results/edit/:id', to: 'results#edit', as: :edit_result
  post 'results/update', to: 'results#update', as: :update_result

  post 'questions_multiple_choice/create', to: 'questions#multiple_choice_create'
  post 'questions-section/create', to: 'questions#question_section_create'

  match 'print',  to: 'print_report#index', via: [:get, :post], as: :print_search
  get 'print/report', to: 'print_report#print_report'
  get 'print/single-report', to: 'print_report#print_single_report'
  match 'question-sections',  to: 'question_sections#index', via: [:get, :post], as: :question_sections_search
  post 'question-sections/create', to: 'question_sections#result_create'
  post 'question-sections/delete/:id', to: 'question_sections#delete', as: :delete_question_sections
  get 'question-sections/edit/:id', to: 'question_sections#edit', as: :edit_question_sections
  post 'question-sections/update', to: 'question_sections#update', as: :update_question_sections

  match 'years',  to: 'years#index', via: [:get, :post], as: :years_search
  post 'years/create', to: 'years#result_create'
  post 'years/delete/:id', to: 'years#delete', as: :delete_years
  get 'years/edit/:id', to: 'years#edit', as: :edit_years
  post 'years/update', to: 'years#update', as: :update_years

  match 'courses',  to: 'courses#index', via: [:get, :post], as: :courses_search
  post 'courses/create', to: 'courses#result_create'
  post 'courses/delete/:id', to: 'courses#delete', as: :delete_courses
  get 'courses/edit/:id', to: 'courses#edit', as: :edit_courses
  post 'courses/update', to: 'courses#update', as: :update_courses

  match 'sections',  to: 'sections#index', via: [:get, :post], as: :sections_search
  post 'sections/create', to: 'sections#result_create'
  post 'sections/delete/:id', to: 'sections#delete', as: :delete_sections
  get 'sections/edit/:id', to: 'sections#edit', as: :edit_sections
  post 'sections/update', to: 'sections#update', as: :update_sections

   get 'settings', to: 'users#setting'

  get 'myquestions/index'

  get 'myquestions/create'

  get 'myquestions/update'

  get 'myquestions/delete'

  get 'terms-conditions', to: 'home#terms_conditions'

  root 'home#index'

end

app/models/result.rb
class Result < ActiveRecord::Base
	  validates_presence_of :title, :description
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	  before_action :authenticate_user!
    before_action :authenticate_role

  def index
  	@page_header = "Result Management"
  	@page_desc = "Create new Results"
    if params[:title].blank?
  	@result = Result.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  else
        @result = Result.where(status: "active").order("id desc").where("lower(title) like '%#{params[:title].downcase}%' or lower(description) like '%#{params[:title].downcase}%' ").paginate(:page => params[:page], :per_page => 15)
  end
  end

  def result_create
  	@result = Result.new(r_params)
  	if @result.save
  	@re3sult = true
  	end
  	@result = Result.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  	render :layout => false
  end

  def delete

  	@r =  Result.update(params[:id], status: "archived")
    # @upt = UserPrepareTest.where(test_id: params[:id])
    # @ut =  UserTest.where(user_prepare_test_id: @upt.map(&:id))
    # @qa =  QuestionAnswer.where(answer_result: params[:id])
    # @q = Question.where(id: @qa.map(&:question_id))
    # @upt.destroy_all if @upt.present?
    # @ut.destroy_all if @ut.present?
    # @qa.destroy_all if @qa.present?
    # @q.destroy_all if @q.present?


  	@result = Result.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  	render :layout => false
  end

  def edit
    @page_header = "Result Management"
    @page_desc = "Edit Results"
    @edit_result = Result.find(params[:id])
    @result = Result.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  end

  def update
    if @r3sult = Result.update(params[:result_id],r_params)
    end
    @result = Result.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
    render :layout => false
   
  end

private
  
  def r_params
    params.require(:results).permit(:title, :description)
  end

end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_result_pagination.html.erb
<%= will_paginate @result, renderer: BootstrapPagination::Rails %>

app/views/results/_result_partial.html.erb
<table class="table table-hover">
  <tbody><tr>
    <th>Result Title</th>
    <th>Description</th>
    <th>Published</th>
    <th>Actions</th>
  </tr>
  <%@result.each do |t|%>
    <tr>
      <td><%=t.title%></td>
      <td><%=simple_format(t.description)%></td>
      <td><%=t.created_at.to_date.strftime("%m-%d-%Y")%></td>
      <td>
      <div class="width-130">
      <a class="btn btn-warning " data-toggle="tooltip" title="Edit" href="/results/edit/<%=t.id%>" role="button"><i class="fa fa-edit"></i></a>
     <%= link_to "<i class='fa fa-archive'></i>".html_safe, delete_result_path(t.id),  data: {confirm: "Archive #{t.title}?"}, :method => :post, class: "btn btn-danger", remote: true, "data-toggle" => "tooltip", :title => "Archive", "data-caption" => "Yes, archive it"  %>

       </div>   
      </td>
    </tr>
  <%end%>
</tbody></table>

app/views/results/delete.js.erb
$('.result-ajax').html("<%= escape_javascript(render partial: 'result_partial',  :locals => { :result => @result}) %>");

swal(
  'Good job!',
  'Successfully Archived!',
  'success'
)


$('#results-form')[0].reset();

app/views/results/edit.html.erb
<div class="info-box"> 
  <div class="content">
     <%= form_for :results, url: update_result_path, :html => {id: "results-form", class: "form-horizontal", :multipart => true}, remote: true do |f| %>
             <%=hidden_field_tag :result_id, params[:id]%>

          <div class="form-group has-feedback required">
              <%=f.label :title, class: "col-sm-2"%>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_field :title, value: @edit_result.title, :class => 'form-control' %>
              <!-- <span class="help-block pull-right"><span class="counttitle">0</span>/70 </span> -->
            </div>
          </div>

          <div class="form-group has-feedback required">
              <%=f.label :description, "Description:", class: "col-sm-2"%>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_area :description, value: @edit_result.description, :class => 'ckeditor form-control' %>
              <!-- <span class="help-block pull-right"><span class="counttitle">0</span>/70 </span> -->
            </div>
          </div>


        <div class="form-group">
        <div class="col-sm-offset-2  col-sm-10 col-lg-offset-2 col-lg-9">
          <button class="btn btn-primary btn-flat" type="submit" name="commit" value="save"> <i class='fa fa-savex'></i> Save Changes
          </button>
      
          <!-- <button class="btn btn-danger  btn-flat" type="reset" value="Reset"> <i class='fa fa-cancel'></i> Cancel
          </button> -->
        </div>
        </div>
      </div>
       <%end%>
  </div>
  <div class="row">
        <div class="col-xs-12">
          <div class="box box-main">
            <div class="box-header with-border">
              <h3 class="box-title">Results</h3>
              <div class="box-tools">
                <div class="input-group input-group-sm">
                  <!-- <input type="text" placeholder="Search" class="form-control pull-right" name="table_search"> -->
                  <div class="input-group-btn">
                    <a href="/results" class="btn btn-default"><i class="fa fa-level-up" aria-hidden="true"></i> Back
</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="box-body table-responsive no-padding result-ajax">
                <%=render partial: 'result_partial',  :locals =>  {:result => @result}%>
            </div>
              <div class="box-footer">
                    <%= will_paginate @result, renderer: BootstrapPagination::Rails %>
              </div>
          </div>
        </div>
  </div>






<!-- Modal for create section -->
<div class="modal fade" id="q_section_modal" tabindex="1" role="dialog" aria-labelledby="myModalLabel2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2"><i class="fa fa-file-text-o"></i> Create Section</h4>
      </div>

      <%= form_for :question_section, url: questions_section_create_path, :html => {id: "q_section_form", class: "form-horizontal", :multipart => true}, :remote => true do |f| %>
      <div class="modal-body">
        
          <div class="form-group has-feedback required">
              <%=f.label :question_section_name, "Question Section:", class: "col-sm-3 control-label"%>
            <div class="col-sm-10 col-lg-8">
              <%= f.text_field :question_section_name, :class => 'form-control' %>
              <span class="help-block pull-right">Enter Question Section Name</span>
            </div>
          </div>

      </div>
      
      <div class="modal-footer">
       <!-- <button type="button" class="btn btn-default btn-flat" type="submit" name="commit" value="Save">Save</button> -->
       <%= f.submit "Save", class: "btn btn-default btn-flat" %>
        <!-- <button class="btn btn-default btn-flat" data-dismiss="modal" >Cancel</button> -->

      </div>
      <%end%>
    </div>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function() {
    CKEDITOR.replace( 'results_description' );
});
</script>

app/views/results/index.html.erb
<div class="info-box"> 
  <div class="content">
     <%= form_for :results, url: results_create_path, :html => {id: "results-form", class: "form-horizontal", :multipart => true}, remote: true do |f| %>


          <div class="form-group has-feedback required">
              <%=f.label :title, class: "col-sm-2"%>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_field :title, :class => 'form-control' %>
              <!-- <span class="help-block pull-right"><span class="counttitle">0</span>/70 </span> -->
            </div>
          </div>

          <div class="form-group has-feedback required">
              <%=f.label :description, "Description:", class: "col-sm-2"%>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_area :description, :class => 'ckeditor form-control' %>
              <!-- <span class="help-block pull-right"><span class="counttitle">0</span>/70 </span> -->
            </div>
          </div>


        <div class="form-group">
        <div class="col-sm-offset-2  col-sm-10 col-lg-offset-2 col-lg-9">
          <button class="btn btn-primary btn-flat" type="submit" name="commit" value="save"> <i class='fa fa-savex'></i> Add New Result
          </button>
      
          <!-- <button class="btn btn-danger  btn-flat" type="reset" value="Reset"> <i class='fa fa-cancel'></i> Cancel
          </button> -->
        </div>
        </div>
      </div>
       <%end%>
  </div>
  <div class="row">
        <div class="col-xs-12">
          <div class="box box-main">
            <div class="box-header with-border">
              <h3 class="box-title">Results</h3>
              <div class="box-tools">
               <%=form_tag(result_search_path, method: "GET", :id => "search-inputx", remote: true ) do -%>   
                <div style="width: 200px;" class="input-group input-group-sm">
                  <div class="input-group-btn">
                    <a href="/results" class="btn btn-default"><i class="fa fa-refresh"></i></a>
                  </div>
                    <%= text_field_tag(:title, nil, class: 'form-control pull-right',  placeholder: 'Search result', value: params[:title]) -%>
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                  </div>
              </div>
               <%end%>
            </div>
            </div>
            <div class="box-body table-responsive no-padding result-ajax">
                <%=render partial: 'result_partial',  :locals =>  {:result => @result}%>
            </div>
              <div class="box-footer resul_pagination">
                    <%= will_paginate @result, renderer: BootstrapPagination::Rails %>
              </div>
          </div>
        </div>
  </div>

app/views/results/index.js.erb
$('.result-ajax').html("<%= escape_javascript(render partial: 'result_partial',  :locals => { :result => @result}) %>");
$('.resul_pagination').html("<%= escape_javascript(render partial: 'result_pagination',  :locals => { :result => @result}) %>");

app/views/results/result_create.js.erb
<%if @re3sult == true%>
$('.result-ajax').html("<%= escape_javascript(render partial: 'result_partial',  :locals => { :result => @result}) %>");

$('#results-form')[0].reset();
for (instance in CKEDITOR.instances){
   CKEDITOR.instances[instance].setData(" ");
}
swal(
  'Good job!',
  'Successfully Saved!',
  'success'
)


<%else%>
swal(
  'Oops...',
  'Please check your entries or fill up the blanks before you submit, and try again.',
  'error'
)

<%end%>

app/views/results/update.js.erb
 <%if @r3sult.errors.any?%>
swal(
  'Oops...',
  'Something went wrong!',
  'error'
)

<%else%>

$('.result-ajax').html("<%= escape_javascript(render partial: 'result_partial',  :locals => { :result => @result}) %>");

swal(
  'Good job!',
  'Successfully Updated!',
  'success'
)
<%end%>