config/routes.rb
Rails.application.routes.draw do
    

  match 'user-test',  to: 'user_test#index', via: [:get, :post], as: :user_test_search
  get 'user-test/new', to: 'user_test#new'
  post 'user-test/create', to: 'user_test#create'

  get 'user-test/search_user', to: 'user_test#search_user'

  match 'analytics',  to: 'analytics#index', via: [:get, :post], as: :analytic_search
  get 'analytics/view/:id', to: 'analytics#show'
  post 'analytics/retake/:id', to: 'analytics#retake', as: :retake_user_analytic
  post 'analytics/delete/:id', to: 'analytics#delete', as: :delete_user_analytic

  get 'dashboard', to: "users#dashboard", as: :dashboard
  match 'user-candidates',  to: 'users#index', via: [:get, :post], as: :user_search
  get  'users/new',  to: 'users#new'
  post  'users/delete/:id',  to: 'users#delete', as: :delete_user
  get  'users/edit/:id',  to: 'users#edit'
  get  'users/invite/:id',  to: 'users#edit'
  patch 'users/update',  to: 'users#update', as: :update_user
  post 'users/create',  to: 'users#add_user'

 
  get 'result', to: 'take_test#result'
  get 'take-test/:id', to: 'take_test#take_test'
  post 'submit-test', to: "take_test#submit_test", as: :submit_test
  get 'profile', to: "take_test#profile", as: :profile
  post 'update-profile',  to: 'take_test#update_profile', as: :update_profile

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => { :registrations => 'member_registrations' }

  get 'test-library/preview-test/:id', to: 'tests#preview_test'

  match 'test-library',  to: 'tests#index', via: [:get, :post], as: :test_search

  post 'test-library/delete/:id', to: 'tests#delete_test', as: :delete_test_index

  get 'tests/new/:id', to: "tests#new", as: :new_test

  delete 'tests/delete/:id', to: "tests#delete", as: :delete_test

  post 'tests/update_status/:id', to: "tests#update_status"

  post 'tests/create', to: "tests#create"

  post 'tests/create_test_question', to: "tests#create_test_question"

  mount Ckeditor::Engine => '/ckeditor'
  match 'questions',  to: 'questions#index', via: [:get, :post], as: :question_search
  get 'questions/new', to: 'questions#multiple_choice'
  post 'questions/delete/:id', to: 'questions#delete_multiple_choice', as: :delete_question
  get 'questions/edit/:id', to: 'questions#edit_multiple_choice', as: :edit_question
  post 'questions/update', to: 'questions#update_multiple_choice', as: :update_question
   match 'results',  to: 'results#index', via: [:get, :post], as: :result_search
  post 'results/create', to: 'results#result_create'
  post 'results/delete/:id', to: 'results#delete', as: :delete_result
  get 'results/edit/:id', to: 'results#edit', as: :edit_result
  post 'results/update', to: 'results#update', as: :update_result

  post 'questions_multiple_choice/create', to: 'questions#multiple_choice_create'
  post 'questions-section/create', to: 'questions#question_section_create'

  match 'print',  to: 'print_report#index', via: [:get, :post], as: :print_search
  get 'print/report', to: 'print_report#print_report'
  get 'print/single-report', to: 'print_report#print_single_report'
  match 'question-sections',  to: 'question_sections#index', via: [:get, :post], as: :question_sections_search
  post 'question-sections/create', to: 'question_sections#result_create'
  post 'question-sections/delete/:id', to: 'question_sections#delete', as: :delete_question_sections
  get 'question-sections/edit/:id', to: 'question_sections#edit', as: :edit_question_sections
  post 'question-sections/update', to: 'question_sections#update', as: :update_question_sections

  match 'years',  to: 'years#index', via: [:get, :post], as: :years_search
  post 'years/create', to: 'years#result_create'
  post 'years/delete/:id', to: 'years#delete', as: :delete_years
  get 'years/edit/:id', to: 'years#edit', as: :edit_years
  post 'years/update', to: 'years#update', as: :update_years

  match 'courses',  to: 'courses#index', via: [:get, :post], as: :courses_search
  post 'courses/create', to: 'courses#result_create'
  post 'courses/delete/:id', to: 'courses#delete', as: :delete_courses
  get 'courses/edit/:id', to: 'courses#edit', as: :edit_courses
  post 'courses/update', to: 'courses#update', as: :update_courses

  match 'sections',  to: 'sections#index', via: [:get, :post], as: :sections_search
  post 'sections/create', to: 'sections#result_create'
  post 'sections/delete/:id', to: 'sections#delete', as: :delete_sections
  get 'sections/edit/:id', to: 'sections#edit', as: :edit_sections
  post 'sections/update', to: 'sections#update', as: :update_sections

   get 'settings', to: 'users#setting'

  get 'myquestions/index'

  get 'myquestions/create'

  get 'myquestions/update'

  get 'myquestions/delete'

  get 'terms-conditions', to: 'home#terms_conditions'

  root 'home#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	  before_action :authenticate_user!
    before_action :authenticate_role

  def index
  	@page_header = "Course Management"
  	@page_desc = "Create new Course"
    if params[:course_name].blank?
  	@course = Course.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  else
        @course = Course.where(status: "active").order("id desc").where("lower(course_name) like '%#{params[:course_name].downcase}%'").paginate(:page => params[:page], :per_page => 15)
  end
  end

  def result_create
  	@course = Course.new(r_params)
  	if @course.save
  	@cours3 = true
  	end
  	@course = Course.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  	render :layout => false
  end

  def delete
  	@r =  Course.update(params[:id], status: "archived")
  	@course = Course.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  	render :layout => false
  end

  def edit
    @page_header = "Course Management"
    @page_desc = "Edit Course"
    @edit_course = Course.find(params[:id])
    @course = Course.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
  end

  def update
    if @cours3 = Course.update(params[:course_id],r_params)
    end
    @course = Course.where(status: "active").order("id desc").paginate(:page => params[:page], :per_page => 15)
    render :layout => false
   
  end

private
  
  def r_params
    params.require(:courses).permit(:course_name)
  end

end

app/views/courses/_course_pagination.html.erb
<%= will_paginate @course, renderer: BootstrapPagination::Rails %>

app/views/courses/_course_partial.html.erb
<table class="table table-hover">
  <tbody><tr>
    <th>Course</th>
    <th>Published</th>
    <th>Actions</th>
  </tr>
  <%@course.each do |t|%>
    <tr>
      <td><%=t.course_name%></td>
      <td><%=t.created_at.to_date.strftime("%m-%d-%Y")%></td>
      <td>
      <div class="width-130">
      <a class="btn btn-warning " data-toggle="tooltip" title="Edit" href="/courses/edit/<%=t.id%>" role="button"><i class="fa fa-edit"></i></a>
     <%= link_to "<i class='fa fa-archive'></i>".html_safe, delete_courses_path(t.id),  data: {confirm: "Archive #{t.course_name}?"}, :method => :post, class: "btn btn-danger", remote: true, "data-toggle" => "tooltip", :title => "Archive", "data-caption" => "Yes, archive it"  %>

       </div>   
      </td>
    </tr>
  <%end%>
</tbody></table>

app/views/courses/delete.js.erb
$('.result-ajax').html("<%= escape_javascript(render partial: 'course_partial',  :locals => { :course => @course}) %>");

swal(
  'Good job!',
  'Successfully Archived!',
  'success'
)

app/views/courses/edit.html.erb
<div class="info-box"> 
  <div class="content content-setting">
     <%= form_for :courses, url: update_courses_path, :html => {id: "results-form", class: "form-horizontal", :multipart => true}, remote: true do |f| %>
             <%=hidden_field_tag :course_id, params[:id]%>

          <div class="form-group has-feedback required">
              <%=f.label :course_name, "Course", class: "col-sm-2"%>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_field :course_name, value: @edit_course.course_name, :class => 'form-control' %>
              <!-- <span class="help-block pull-right"><span class="counttitle">0</span>/70 </span> -->
            </div>
          </div>



        <div class="form-group">
        <div class="col-sm-offset-2  col-sm-10 col-lg-offset-2 col-lg-9">
          <button class="btn btn-primary btn-flat" type="submit" name="commit" value="save"> <i class='fa fa-savex'></i> Save Changes
          </button>
      
          <!-- <button class="btn btn-danger  btn-flat" type="reset" value="Reset"> <i class='fa fa-cancel'></i> Cancel
          </button> -->
        </div>
        </div>
      </div>
       <%end%>
  </div>
  <div class="row">
        <div class="col-xs-12">
          <div class="box box-main">
            <div class="box-header with-border">
              <h3 class="box-title">Results</h3>
              <div class="box-tools">
                <div class="input-group input-group-sm">
                  <!-- <input type="text" placeholder="Search" class="form-control pull-right" name="table_search"> -->
                  <div class="input-group-btn">
                    <a href="/courses" class="btn btn-default"><i class="fa fa-level-up" aria-hidden="true"></i> Back
</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="box-body table-responsive no-padding result-ajax">
                <%=render partial: 'course_partial',  :locals =>  {:course => @course}%>
            </div>
              <div class="box-footer">
                    <%= will_paginate @course, renderer: BootstrapPagination::Rails %>
              </div>
          </div>
        </div>
  </div>

app/views/courses/index.html.erb
<div class="info-box"> 
  <div class="content content-setting">
     <%= form_for :courses, url: courses_create_path, :html => {id: "results-form", class: "form-horizontal", :multipart => true}, remote: true do |f| %>


          <div class="form-group has-feedback required">
              <%=f.label :course_name, "Course", class: "col-sm-2"%>
            <div class="col-sm-10 col-lg-10">
              <%= f.text_field :course_name, :class => 'form-control' %>
              <!-- <span class="help-block pull-right"><span class="counttitle">0</span>/70 </span> -->
            </div>
          </div>
        <div class="form-group">
        <div class="col-sm-offset-2  col-sm-10 col-lg-offset-2 col-lg-9">
          <button class="btn btn-primary btn-flat" type="submit" name="commit" value="save"> <i class='fa fa-savex'></i> Add New Course
          </button>
      
          <!-- <button class="btn btn-danger  btn-flat" type="reset" value="Reset"> <i class='fa fa-cancel'></i> Cancel
          </button> -->
        </div>
        </div>
      </div>
       <%end%>
  </div>
  <div class="row">
        <div class="col-xs-12">
          <div class="box box-main">
            <div class="box-header with-border">
              <h3 class="box-title">Courses</h3>
              <div class="box-tools">
               <%=form_tag(courses_search_path, method: "GET", :id => "search-inputx", remote: true ) do -%>   
                <div style="width: 200px;" class="input-group input-group-sm">
                  <div class="input-group-btn">
                    <a href="/courses" class="btn btn-default"><i class="fa fa-refresh"></i></a>
                  </div>
                    <%= text_field_tag(:course_name, nil, class: 'form-control pull-right',  placeholder: 'Search course', value: params[:course_name]) -%>
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                  </div>
              </div>
               <%end%>
            </div>
            </div>
            <div class="box-body table-responsive no-padding result-ajax">
                <%=render partial: 'course_partial',  :locals =>  {:course => @course}%>
            </div>
              <div class="box-footer resul_pagination">
                    <%= will_paginate @course, renderer: BootstrapPagination::Rails %>
              </div>
          </div>
        </div>
  </div>

app/views/courses/index.js.erb
$('.result-ajax').html("<%= escape_javascript(render partial: 'course_partial',  :locals => { :course => @course}) %>");
$('.resul_pagination').html("<%= escape_javascript(render partial: 'course_pagination',  :locals => { :course => @course}) %>");

app/views/courses/result_create.js.erb
<%if @cours3 == true%>
$('.result-ajax').html("<%= escape_javascript(render partial: 'course_partial',  :locals => { :course => @course}) %>");
 $('#results-form')[0].reset();
swal(
  'Good job!',
  'Successfully Saved!',
  'success'
)


<%else%>
swal(
  'Oops...',
  'Please check your entries or fill up the blanks before you submit, and try again.',
  'error'
)

<%end%>

app/views/courses/update.js.erb
 <%if @cours3.errors.any?%>
swal(
  'Oops...',
  'Something went wrong!',
  'error'
)

<%else%>

$('.result-ajax').html("<%= escape_javascript(render partial: 'course_partial',  :locals => { :course => @course}) %>");

swal(
  'Good job!',
  'Successfully Updated!',
  'success'
)
<%end%>